### ISSUE TITLE
Storybook 6.5 support

### ISSUE THREAD

**Issue by cosmicdreams** [Lullabot/storybook-drupal-addon#31]
There appears to be an issue with this addon working properly with Storybook 6.5.  Specifically I get this error:

```
ERR! TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of Object
ERR!     at new NodeError (internal/errors.js:322:7)
ERR!     at validateString (internal/validators.js:124:11)
ERR!     at Module.require (internal/modules/cjs/loader.js:996:3)
ERR!     at require (internal/modules/cjs/helpers.js:107:18)
ERR!     at interopRequireDefault (/var/www/html/node_modules/@storybook/core-common/dist/cjs/presets.js:178:16)
ERR!     at getContent (/var/www/html/node_modules/@storybook/core-common/dist/cjs/presets.js:194:10)
ERR!     at loadPreset (/var/www/html/node_modules/@storybook/core-common/dist/cjs/presets.js:203:20)
ERR!     at /var/www/html/node_modules/@storybook/core-common/dist/cjs/presets.js:256:18
ERR!     at Array.reduce (<anonymous>)
ERR!     at loadPresets (/var/www/html/node_modules/@storybook/core-common/dist/cjs/presets.js:255:18)
```

When I remove this addon from my main.js's list of addons I no longer get this error.  I'm not 100% certain, but I think that means this error is caused by this addon.

When I research this error I get responses like https://stackoverflow.com/questions/62015605/failed-to-load-preset-storybook-addon-info-on-level-1

..which seems to advocate for migrating away from addon-info and use addon-docs instead.  Also, this step appears to be a key step towards migrating to Storybook 7.

**Comment by theodorosploumis** [comment]
Actually, we use **Storybook 7.x** for a long time now and we have no issues. This may be an issue with your local setup and not this plugin.
